### ISSUE TITLE
geometryangle.tritoncode.com is down

### ISSUE THREAD

**Issue by onlineth** [TritonCode/jquery-fss#3]
The subdomain, http://geometryangle.tritoncode.com/, is down
http://downforeveryoneorjustme.com/geometryangle.tritoncode.com

**Comment by onlineth** [comment]
Still down...

**Comment by pats2sats** [comment]
@onlineth Will be back up in a couple of minutes, switched to hosted server - sorry for the inconvenience and thanks for the continued interest!

**Comment by onlineth** [comment]
It's up, thanks:)
